// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jbakhtin/marketplace-cart/internal/modules/cart/domain"
	mock "github.com/stretchr/testify/mock"
)

// LomsService is an autogenerated mock type for the LomsService type
type LomsService struct {
	mock.Mock
}

// StockInfo provides a mock function with given fields: ctx, sku
func (_m *LomsService) StockInfo(ctx context.Context, sku domain.SKU) (domain.StockInfo, error) {
	ret := _m.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for StockInfo")
	}

	var r0 domain.StockInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SKU) (domain.StockInfo, error)); ok {
		return rf(ctx, sku)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SKU) domain.StockInfo); ok {
		r0 = rf(ctx, sku)
	} else {
		r0 = ret.Get(0).(domain.StockInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SKU) error); ok {
		r1 = rf(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLomsService creates a new instance of LomsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLomsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LomsService {
	mock := &LomsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
