// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jbakhtin/marketplace-cart/internal/modules/cart/domain"
	mock "github.com/stretchr/testify/mock"
)

// ProductService is an autogenerated mock type for the ProductService type
type ProductService struct {
	mock.Mock
}

// GetProduct provides a mock function with given fields: ctx, sku
func (_m *ProductService) GetProduct(ctx context.Context, sku domain.SKU) (domain.ProductInfo, error) {
	ret := _m.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 domain.ProductInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SKU) (domain.ProductInfo, error)); ok {
		return rf(ctx, sku)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SKU) domain.ProductInfo); ok {
		r0 = rf(ctx, sku)
	} else {
		r0 = ret.Get(0).(domain.ProductInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SKU) error); ok {
		r1 = rf(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductService creates a new instance of ProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductService {
	mock := &ProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
